### ISSUE TITLE
jupyterlab support

### ISSUE THREAD

**Issue by dhirschfeld** [altair-viz/pdvega#22]
> *the current version of pdvega will not work in JupyterLab: the main reason is that the new MIME-based rendering used by JupyterLab is not yet supported in the vega3 library that pdvega depends on*

Just wanted to clarify that this is correct, *even* with the [`vega3`](https://github.com/jupyterlab/jupyter-renderers/tree/master/packages/vega3-extension) jupyterlab extension?

If that is the case I guess this can be kept open to track any progress...

**Comment by jakevdp** [comment]
Yes, this is true that pdvega is incompatible with JupyterLab.

The fix will be to display plots using the tools in Altair 2.0 once it's released.

**Comment by stonebig** [comment]
is there a rough guesss of Altair-2.0 release ? March 1rst ? April ? June ?

**Comment by jakevdp** [comment]
Well, I'm giving a PyCon tutorial on Altair 2, so I'd say... before that 😄

**Comment by domoritz** [comment]
:tada:

**Comment by stonebig** [comment]
ok: may the 4th be with us

**Comment by fndari** [comment]
Hi, just wanted to check if there was any update re: JupyterLab compatibility. I think this project fills a very useful niche, especially for notebook-heavy workflows, and would like to know if there's any progress and/or roadmap on this.

**Comment by jakevdp** [comment]
Yes, currently the master branch relies on Altair for rendering, and Altair rendering is compatible with Jupyterlab.

**Comment by jakevdp** [comment]
I think so
